services:
  pesula-bot:
    image: ghcr.io/aseevlx/pesula-notifications-bot:latest
    container_name: pesula-bot
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./storage.db:/app/storage.db
